leave = "Verlassen"
restart_pl = "Neustart"
watch_others = "Beobachte andere Spieler"
minesweeper = "Minesweeper"

book_page_1 = """
§2§nMinesweeper

§rDas Ziel ist es, alle Felder zu enthüllen. Dabei darfst du keine Bombe aktivieren.

Die Zahlen zeigen dir, wie viele Bomben sich in einem 3x3 Bereich befinden."""
book_page_2 = """
§2§nVerwendung:§r

§9§oLinksklick§r um ein Feld aufzudecken.

§r§9§oRechtsklick§r, um eine Flagge zu platzieren.
§8->Damit markierst du
   die Bomben und
   kannst sie nicht
   mehr aktivieren.
->Entfernen mit
   erneutem Rechtklick."""
book_page_3 = """
§9§oDoppel Linksklick§r, um
alle umliegenden Felder aufzudecken.
§8-> Nur möglich, wenn in
den umliegenden
Feldern alle Bomben
markiert sind."""
book_tutorial = "Anleitung"
book_title = "Minesweeper - Anleitung"
hour_glass_display_name = "Starte ein Spiel"
easy = "§2Easy"
normal = "§eMedium"
hard = "§cHard"
field_desc = "Größe: {0}x{1} | Bomben: {2}"
resource_pack_error = "Ein Fehler ist beim Herunterladen des Texturpakets aufgetreten, bitte den Server erneut betreten."
resource_pack_not_enabled = "Das Herunterladen des Server-Texturpakets ist erforderlich, um dieses Minispiel zu spielen. Bitte erlaube dies in den Spieloptionen und betrete den Server erneut."
message_win = "Du hast das Spiel gewonnen!"
message_time_needed = "Benötigte Zeit: {0}"

title_win = "Du hast gewonnen!"

player = "player"
game = "game"
custom = "benutzerdefiniert"
default = "Standard"
default_setting = "Standardeinstellung"
true_ = "true"
false_ = "false"
enabled = "aktiviert"
disabled = "deaktiviert"
settings = "Einstellungen"

use_multi_flag = "Mehrere Flaggen"
reveal_on_double_click = "Doppelklick aufdecken"
hide_player_distance = "Spieler-Versteck Distanz"
hide_player = "Verstecke Spieler"
quick_reveal = "Schnelles aufdecken"
enable_flag = "Flaggen"
enable_question_mark = "Fragezeichen"
board_style = "Board Style"
quick_reveal_duration = "Schnellaufdeck Dauer"
custom_resource_pack_url = "Eigenes Resourcepack"
break_flags = "Zerstöre Flaggen"
hide_while_in_game = "Verstecke Spieler nur während eines Spiels"

send_current_setting_number = "Deine aktuelle {0} ist {1}."
send_current_setting_boolean = "Derzeit ist {0} {1}."
send_was_applied = "Die angegebene {0} wurde angewendet."
send_change_enable = "{0} wurde aktiviert."
send_change_disable = "{0} wurde deaktiviert."
send_current_board_style = "Dein aktueller Board-Stil ist: {0}."
send_board_style_applied = "Der angegebene Board-Stil wurde angewendet."
send_unknown_error = "Ein unbekannter Fehler ist aufgetreten."
send_current_resource_pack_url = "Deine aktuelle URL des Texturpakets lautet: {0}"
send_start_with_http = "Stell bitte sicher, dass die URL mit 'http://' oder 'https://' beginnt."
send_resource_pack_applied = "Die angegebene URL des Texturpakets wurde angewendet."

send_invite_player = "Du wurdest von {0} zu einem Duell eingeladen. Gebe /mineduel accept {0} ein um diesem beizutreten."
broadcast_invite = "{0} wurde eingeladen."
broadcast_accept = "{0} ist dem Duell beigetreten."
send_leave = "Du hast das Duell von {0} verlassen."
broadcast_leave = "{0} hat das Duell verlassen."
send_kick = "Du wurdest aus dem Duell von {0} gekickt."
broadcast_kick = "{0} hat das Duell verlassen."
broadcast_game = "Das Duell findet nun auf der Map {0} statt."
broadcast_start = "Das Duell hat gestartet. Viel Glück!"

duel_invite = "invite"
duel_accept = "accept"
duel_leave = "leave"
duel_kick = "kick"
duel_game = "game"
duel_start = "start"

minesweeper_command_custom_completion = "/{0} custom [Bombenanzahl] [BreiteXHöhe] <Seed>"

error_already_generated = "Das Feld wurde bereits generiert."
error_bomb_exploded = "Die Bombe bei {0} und {1} ist explodiert."
error_not_determine_player_name = "Der Spielername konnte nicht bestimmt werden. Bitte versuche es später erneut."
error_specify_map = "Bitte gib eine Karte an."
error_custom_game_unavailable = "Benutzerdefiniertes Spiel ist derzeit nicht verfügbar."

error_no_true_or_false = "Es wurde kein wahr oder falsch als Argument gefunden, deshalb wird der Befehl ignoriert."

error_no_permission = "Du hast keine Berechtigung, diesen Befehl auszuführen."
error_no_valid_number = "Bitte gib eine gültige ganze Zahl an."
error_bomb_size_not_valid = "Die Bombenanzahl ist für die angegebene Kartengröße ungültig."
error_bomb_size_too_big = "Die angegebene Bombenanzahl ist zu groß."
error_bomb_size_too_small = "Die Anzahl der Bomben muss größer als Null sein."