leave = "Leave"
restart_pl = "Restart"
watch_others = "Watch other players"
minesweeper = "Minesweeper"

book_page_1 = """
§2§nMinesweeper

§rThe goal is to uncover all the squares. You must not activate any bombs.

The numbers show you how many bombs are in a 3x3 area."""
book_page_2 = """
§2§nUse:§r

§9§oLeft click§r to reveal a field.

§r§9§oRight click§r to place a flag.
§8-> With the flag you
    mark the bombs
    and cannot
    activate them
    anymore.
-> Remove with
    right click."""
book_page_3 = """
§9§oDouble left click§r to
reveal all surrounding fields.
§8-> Only possible if in
    the surounding
    fields all bombs
    are marked."""
book_tutorial = "Tutorial"
book_title = "Minesweeper - Tutorial"
hour_glass_display_name = "Start a game"
easy = "§2Easy"
normal = "§eMedium"
hard = "§cHard"
field_desc = "Size: {0}x{1} | Bombs: {2}"
resource_pack_error = "An error occurred while downloading the texture pack, please re-enter the server."
resource_pack_not_enabled = "Downloading the server texture pack is required to play this mini-game. Please allow this in the game options and re-enter the server."
message_win = "You won the game!"
message_time_needed = "Time required: {0}"
title_win = "You have won!"

player = "player"
game = "game"
custom = "custom"
default = "default"
default_setting = "default setting"
true_ = "true"
false_ = "false"
enabled = "enabled"
disabled = "disabled"

use_multi_flag = "Place multi flags"
reveal_on_double_click = "Reveal on double click"
hide_player_distance = "Hide player distance"
hide_player = "Hide players"
quick_reveal = "Quick reveal"
enable_flag = "Enable flags"
enable_question_mark = "Enable question mark"
board_style = "Board style"
quick_reveal_duration = "Quick reveal duration"
custom_resource_pack_url = "Custom resourcepack"
break_flags = "Break flags"
hide_while_in_game = "Just hide players while ingame"
restart_on_item_swap = "Press F to restart"

send_current_setting_number = "Your current {0} is {1}."
send_current_setting_boolean = "Currently {0} is {1}."
send_was_applied = "The specified {0} was applied."
send_change_enable = "Enabled {0}."
send_change_disable = "Disabled {0}."
send_current_board_style = "Your current board style is: {0}."
send_board_style_applied = "The specified board style was applied."
send_unknown_error = "An unknown error has occurred."
send_current_resource_pack_url = "Your current resource pack url is: {0}"
send_start_with_http = "Please make sure that the url starts with 'http://' or 'https://'."
send_resource_pack_applied = "The specified resource pack url was applied."

send_invite_player = "You have been invited by {0} to a duel. Type /duel accept {0} to join the duel."
broadcast_invite = "{0} has been invited."
broadcast_accept = "{0} has joined the duel."
send_leave = "You have left the duel by {0}."
broadcast_leave = "{0} has left the duel."
send_Kick = "You have been kicked from the duel by {0}."
broadcast_Kick = "{0} has left the duel."
broadcast_game = "The duel will take place on the map {0}."
broadcast_start = "The duel has started. Good luck!"

duel_invite = "invite"
duel_accept = "accept"
duel_leave = "leave"
duel_Kick = "kick"
duel_game = "game"
duel_start = "start"

minesweeper_command_custom_completion = "/{0} custom [Bomb Count] [WidthXHeight] <Seed>"

error_already_generated = "The field has already been generated."
error_bomb_exploded = "Bomb at {0} and {1} is exploded."
error_not_determine_player_name = "Could not determine the player by its name. Please try again later."
error_specify_map = "Please specify a map."
error_custom_game_unavailable = "Custom game is currently unavailable."

error_no_true_or_false = "No true or false could be found as an argument, so the command is ignored."

error_no_permission = "You don't have the permission to execute this command."
error_no_valid_number = "Please provide a whole number."
error_bomb_size_not_valid = "The bomb count is not valid for the given map size."
error_bomb_size_too_big = "The provided bomb count is too large."
error_bomb_size_too_small = "The number of bombs must be greater than 0."

