language: en_US

resource_pack:
  internal_web_server:
    enable: false
    domain: localhost
    port: 27565
    name: pack.zip
  external_web_server:
    enable: true
    link: https://cdn.discordapp.com/attachments/676083915382849576/875365210997784587/teddy.zip

allow_fly: true
allow_default_watch: true

events:
  cancelEntityDamage: true
  cancelFoodChange: true
  cancelBlockPlace: true
  cancelBlockBreak: true
  cancelInventoryInteract: true
  cancelDropItem: true
  cancelPickupItem: true

location_based:
  enable: false
  actions:
    temporary_fly: true
    cancelled_events:
      cancelEntityDamage: true
      cancelFoodChange: true
      cancelBlockPlace: true
      cancelBlockBreak: true
      cancelInventoryInteract: true
      cancelDropItem: true
      cancelPickupItem: true
  areas:
    - x1: 80
      y1: 10
      z1: -300
      x2: 35
      y2: 40
      z2: -350
      world: MineSweeper



use_default_map: true
available_games_inventory_lines: 1

games:
  Map10x10:
    corner:
      x: 53
      y: 17
      z: -331
      world: MineSweeper
    spawn:
      x: 58
      y: 20
      z: -318.5
      yaw: -180
      pitch: 30
      world: MineSweeper
    border_size: 10
    bomb_count: 10
    difficulty_lang_path: difficulty_easy
    inventory_material: LIME_STAINED_GLASS_PANE
    inventory_position: 2


  Map18x18:
    corner:
      x: 49
      y: 16
      z: -198
      world: MineSweeper
    spawn:
      x: 57
      y: 20
      z: -177.5
      yaw: -180
      pitch: 30
      world: MineSweeper
    border_size: 18
    bomb_count: 40
    difficulty_lang_path: difficulty_normal
    inventory_material: YELLOW_STAINED_GLASS_PANE
    inventory_position: 4

  Map24x24:
    corner:
      x: 49
      y: 14
      z: -63
      world: MineSweeper
    spawn:
      x: 61
      y: 18
      z: -37.5
      yaw: -180
      pitch: 30
      world: MineSweeper
    border_size: 24
    bomb_count: 99
    difficulty_lang_path: difficulty_hard
    inventory_material: RED_STAINED_GLASS_PANE
    inventory_position: 6