language: en_US

resource_pack:
  internal_web_server:
    enable: false
    domain: localhost
    port: 27565
    name: pack.zip
  external_web_server:
    enable: true
    link: https://cdn.discordapp.com/attachments/755817146986004551/1067181025672830986/assets.zip

allow_fly: true
allow_default_watch: true

database:
  host: localhost
  port: 3306
  user: root
  password: password
  database: minesweeper

stats:
  enable: true

events:
  cancelEntityDamage: true
  cancelFoodChange: true
  cancelBlockPlace: true
  cancelBlockBreak: true
  cancelInventoryInteract: true
  cancelDropItem: true
  cancelPickupItem: true

location_based:
  enable: false
  actions:
    temporary_fly: true
    cancelled_events:
      cancelEntityDamage: true
      cancelFoodChange: true
      cancelBlockPlace: true
      cancelBlockBreak: true
      cancelInventoryInteract: true
      cancelDropItem: true
      cancelPickupItem: true
      swapItems: true

  areas:
    - x1: 80
      y1: 10
      z1: -300
      x2: 35
      y2: 40
      z2: -350
      world: MineSweeper



use_default_map: true
map_url: http://plugins.teddybear2004.de:8080/MineSweeper.zip
available_games_inventory_lines: 1
