name: Minesweeper
version: ${project.version}
main: de.teddybear2004.minesweeper.Minesweeper
api-version: 1.19
authors:
  - TeddyBear_2004
  - Wetterquarz
database: false
website: https://github.com/TeddyBear2004/Minesweeper
description: Play Minesweeper in Minecraft
depend:
  - ProtocolLib

libraries:
  - "com.moandjiezana.toml:toml4j:0.7.2"
  - "org.mariadb.jdbc:mariadb-java-client:3.1.0"

commands:
  bypassEventCancellation:
    usage: /bypassEventCancellation
    description: "Bypasses the cancellation of the cancelled events in order to change blocks. 
    Note: This will not work if a game is running."
    permission: minesweeper.bypass.events
  minesweeper:
    usage: "/minesweeper [game]"
    description: "Start a game of minesweeper."
    permission: minesweeper.minesweeper
  settings:
    usage: /settings
    permission: minesweeper.settings
  minestats:
    usage: /minestats <player/game> <player name/game id>
    permission: minesweeper.stats
  mineduel:
    usage: /mineduel
    permission: minesweeper.duel
