name: Minesweeper
version: ${project.version}
main: de.teddy.minesweeper.Minesweeper
api-version: 1.19
authors:
  - TeddyBear_2004
  - Wetterquarz
database: false
website: https://github.com/TeddyBear2004/Minesweeper
description: Play Minesweeper in Minecraft
depend:
  - ProtocolLib

libraries:
  - "com.moandjiezana.toml:toml4j:0.7.2"

commands:
  start:
    usage: /start
    description: Starte ein Spiel
  resetResourcePack:
    usage: /resetResourcePack
    description: Setzt dein aktuelles Server-Resource-Pack zurück.
  bypassEventCancellation:
    usage: /bypassEventCancellation
    description: "Bypasses the cancellation of the cancelled events in order to change blocks. 
    Note: This will not work if a game is running."
    permission: minesweeper.bypass.events
