name: Minesweeper
version: ${project.version}
main: de.teddy.minesweeper.Minesweeper
api-version: 1.19
authors:
  - TeddyBear_2004
  - Wetterquarz
database: false
website: https://github.com/TeddyBear2004/Minesweeper
description: Play Minesweeper in Minecraft
depend:
  - ProtocolLib

commands:
  start:
    usage: /start
    description: Starte ein Spiel
  resetResourcePack:
    usage: /resetResourcePack
    description: Setzt dein aktuelles Server-Resource-Pack zurück.
